//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LangApp.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LangDBEntities : DbContext
    {
        public LangDBEntities()
            : base("name=LangDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COLOR> COLORs { get; set; }
        public virtual DbSet<LANGUAGE> LANGUAGEs { get; set; }
        public virtual DbSet<LANGUAGE_LIST> LANGUAGE_LIST { get; set; }
        public virtual DbSet<MONTH> MONTHs { get; set; }
        public virtual DbSet<PARTS_OF_SPEECH> PARTS_OF_SPEECH { get; set; }
        public virtual DbSet<REGISTER> REGISTERs { get; set; }
        public virtual DbSet<WORD> WORDs { get; set; }
        public virtual DbSet<WORD_CASES> WORD_CASES { get; set; }
        public virtual DbSet<WORD_GROUP> WORD_GROUP { get; set; }
    }
}
